### ISSUE TITLE
Setup project with either NextJS or Gatsby app with Firebase integration for a Blog.

### ISSUE THREAD

**Issue by fahadahmed** [fahadahmed/coding-pixels#1]
# Overview
Setup the project with either NextJS or Gatsby to build a blog app using Contentful as the CMS and Firebase as the backend.

## Tasks
- [x] Setup repo with a new NextJS app
- [x] Initialise Firebase project
- [x] Setup Firebase emulators for local development
- [x] Setup Firebase Functions to integrate third party services
- [ ] Setup ESlint and Prettier for Code Formatting
- [ ] Setup Husky for Pre-commit checks
- [x] Setup Sonarcloud for Code Quality checks

## Additional context
Add any other context or details about the feature request here.

**Comment by fahadahmed** [comment]
This is probably not what I wanted. Changing it to remix app.
